baseURL = 'https://eliasdorneles.com/til/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = 'Today I Learned...'
enableRobotsTXT = true

# List Config
summaryLength= 15
paginate = 5

# See: https://gohugo.io/getting-started/configuration-markup/#highlight
[markup.highlight]
      # codeFences = false
      guessSyntax = true
      # hl_Lines = ""
      # lineNoStart = 1
      # lineNos = false
      # lineNumbersInTable = false
      # tabWidth = 4
      # noClasses = false
