[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3


# Social Media Configuration
[[social]]
    identifier = "my-website"
    name = "About me"
    url = "https://eliasdorneles.com"
    weight = 1

[[social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/eliasdorneles"
    weight = 2
