# Homepage Config
isSinglePage = false

# Meta Config
description = "Hello"

# Header Configuration
avatar = "img/avatar.jpeg"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

 # giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]
    enable = false
